name: Cron Sync Exophase

on:
  schedule:
    - cron: "0 * * * *" # Every hour, change as needed
  workflow_dispatch:     # Allow manual trigger from GitHub UI

jobs:
  ping-vercel-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API to sync Exophase
        run: curl -X POST 'https://exophase-scraper.vercel.app/api/sync'
